export type { DevixConfig, ResolvedDevixConfig } from './config/define-config'
export { defineConfig } from './config/define-config'
export { action, query } from './data'
export type { DevixRootProps } from './hydration/compose'
export { hydrateApp } from './hydration/hydrate'
export { createRenderFn, type RenderHandle } from './server/render-shared'
